site_name: EmuDeck Help
site_url: https://manual.emudeck.com
theme:
  features:
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - toc.integrate
    - navigation.footer
    - navigation.sections
  logo: assets/logo.png
  favicon: assets/app_icon.jpg
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/EmuDeck"
    - icon: "fontawesome/brands/discord"
      link: "https://discord.gg/b9F7GpXtFP"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/EmuDeck"
    - icon: "fontawesome/brands/patreon"
      link: "https://www.patreon.com/dragoonDorise"
  icons:
    custom:
      custom-icon: assets/icons/mi-icono.svg
      custom-other-icon: assets/icons/otro-icono.svg
      custom-android: overrides/.icons/custom-android.svg
      custom-books: overrides/.icons/custom-books.svg
      custom-boot: overrides/.icons/custom-boot.svg
      custom-checker: overrides/.icons/custom-checker.svg
      custom-compress: overrides/.icons/custom-compress.svg
      custom-custom: overrides/.icons/custom-custom.svg
      custom-disk: overrides/.icons/custom-disk.svg
      custom-doc: overrides/.icons/custom-doc.svg
      custom-forbidden: overrides/.icons/custom-forbidden.svg
      custom-help: overrides/.icons/custom-help.svg
      custom-joystick: overrides/.icons/custom-joystick.svg
      custom-list: overrides/.icons/custom-list.svg
      custom-migrate: overrides/.icons/custom-migrate.svg
      custom-package: overrides/.icons/custom-package.svg
      custom-plugin: overrides/.icons/custom-plugin.svg
      custom-prize: overrides/.icons/custom-prize.svg
      custom-question: overrides/.icons/custom-question.svg
      custom-quick: overrides/.icons/custom-quick.svg
      custom-screen: overrides/.icons/custom-screen.svg
      custom-success: overrides/.icons/custom-success.svg
      custom-theme: overrides/.icons/custom-theme.svg
      custom-uninstall: overrides/.icons/custom-uninstall.svg
      custom-warning: overrides/.icons/custom-warning.svg
      custom_gear: assets/.icons/custom-gear.svg

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
nav:
  - What's EmuDeck?: "index.md"
  - Installation Guide:
      - Installing EmuDeck Desktop: "install-guide/1_index.md"
      - Level of integration: "install-guide/2_integration.md"
      - Setting up CloudSync / CloudSaves: "install-guide/3_setting-cloud.md"
      - Copying ROMS and BIOS: "install-guide/4_copying-games.md"
      - Launching games:
          - Playing your games: "install-guide/5_playing-games.md"
          - EmulationStation DE (ES-DE): "install-guide/esde/index.md"
          - Steam Rom Manager (SRM): "install-guide/srm/index.md"
      - Hotkeys: "install-guide/6_hotkeys.md"
  - Getting ROMS:
      - EmuDeck Store: "getting-roms/store.md"
      - Dumping your games: "getting-roms/dump.md"

  - Using the EmuDeck App:
      - Sections:
          - Quick Settings: "using-app/1_quick-settings.md"
          - Manage Emulators: "using-app/2_manage-emulators.md"
          - Import Games & BIOS: "using-app/3_import-games.md"
          - Quick & Custom Reset: "using-app/4-quick-custom-reset.md"
          - Screen Resolution: "using-app/5_screen-resolution.md"
          - Retro Achievements: "using-app/6_retro-achievements.md"
          - Compressor: "using-app/7_compressor.md"
          - Bios Checker: "using-app/8_bios.md"
          - Gaming mode: "using-app/9_gaming-mode.md"
          - Cloud Saves: "using-app/10_cloud_saves.md"
          - Migrate Installation: "using-app/11_migrate_installation.md"
          - Decky plugins: "using-app/12_decky-plugins.md"
          - Cloud Services: "using-app/13_cloud-services.md"

  - Supported Systems:
      - Systems: "supported-systems.md"
      - Emulators: "supported-emulators.md"
  - Other:
      - Cheatsheet: "cheatsheet.md"
      - Troubleshooting: "troubleshooting.md"
      - FAQ: "faq.md"
  - Advanced:
      - Emulators Tips & Tricks:
          - Cemu: "tricks/cemu.md"
          - Citra: "tricks/citra.md"
          - Citron: "tricks/citron.md"
          - Dolphin: "tricks/dolphin.md"
          - Duckstation: "tricks/duckstation.md"
          - Flycast: "tricks/flycast.md"
          - Mame: "tricks/mame.md"
          - MelonDS: "tricks/melonds.md"
          - mGBA: "tricks/mgba.md"
          - Model2: "tricks/model2.md"
          - PCSX2: "tricks/pcsx2.md"
          - PPSSPP: "tricks/ppsspp.md"
          - PrimeHack: "tricks/primehack.md"
          - RetroArch: "tricks/retroarch.md"
          - RMG: "tricks/rmg.md"
          - RPCS3: "tricks/rpcs3.md"
          - Ryujinx: "tricks/ryujinx.md"
          - Supermodel: "tricks/supermodel.md"
          - ShadPS4: "tricks/shadps4.md"
          - Vita3K: "tricks/vita3k.md"
          - Xemu: "tricks/xemu.md"
          - Xenia:: "tricks/xenia.md"
          - Yuzu: "tricks/yuzu.md"
  - Retro Library (Open BETA):
    - What's Retro Library?: "retro-library/1_what-is.md"

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - toc:
      permalink: true
